name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm install

    # 🔗 Link project ke Vercel (sekali aja, lalu tersimpan di .vercel/)
    - name: Link to Vercel Project
      run: npx vercel link --yes --token=${{ secrets.VERCEL_TOKEN }}

    # 🚀 Deploy ke Vercel
    - name: Deploy with Vercel
      run: npx vercel --prod --yes --confirm --token=${{ secrets.VERCEL_TOKEN }}
