# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Continuous Integration

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

      mariadb:
        image: mariadb:latest
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
          MARIADB_DATABASE: hapi_knexjs_dev
          # MARIADB_ROOT_PASSWORD: password
          # MARIADB_USER: usertest
          # MARIADB_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    # Menambahkan langkah SQL untuk membuat tabel "settings"
    - name: Create "settings" Table
      run: |
        mysql -u root -h "127.0.0.1" -P 3306 hapi_knexjs_dev -e "CREATE TABLE IF NOT EXISTS settings (
          id INT AUTO_INCREMENT PRIMARY KEY,
          name VARCHAR(255) NOT NULL,
          value TEXT NOT NULL
        );"

    # Menambahkan langkah penyalinan file konfigurasi
    - name: Copy Configuration File
      run: cp src/config.example.js src/config.js

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install

    - name: Run Development Server
      run: npm run dev & sleep 10 && pkill -f "npm run dev"
